/**
 * Acceptatiecriteria — domein Bezit (WF-BEZIT-01..24 / UAT-BEZIT-01..24).
 *
 * Bron: docs/uat/... Deel 1 (workflow-definities) + Deel 2 (UAT-scenario's met
 * persona-preconditie en uitgeschreven berekening). Cijfers zijn ONAFHANKELIJK
 * narekend uit `lib/test-personas.ts` — nooit overgenomen uit wat de app toont
 * (zie `bezit.engine.test.ts` voor de daadwerkelijke toets tegen de echte
 * rekenfuncties, en het testrapport voor de twee gevonden reken-discrepanties
 * in Deel 2 zelf — WF-BEZIT-17 en WF-BEZIT-23b).
 */

import type { AcceptanceCriterion, AcceptanceSet } from './types'

const criteria: AcceptanceCriterion[] = [
  {
    workflow: 'WF-BEZIT-01',
    scenarioId: 'UAT-BEZIT-01',
    titel: 'Bezittingenoverzicht bekijken: totalen en categorieën',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen (13 bezittingen + 3 bankrekeningen-als-cash = 16 rijen, 13 categoriegroepen).',
    when: 'De gebruiker opent /overzicht/bezittingen (of legacy /core/assets) en leest de figures-strip.',
    then: 'Totale waarde = €1.585.000, Maandelijkse inleg = €1.700, Rendement totaal = €559.000; 13 categoriegroepen, 16 kaarten (Cash-groep bevat 4: 3 rekeningen + de "Spaargeld direct opneembaar"-asset die zelf asset_type "cash" is).',
    assertion: {
      kind: 'exact',
      expected: 'totaleWaarde=1585000; maandelijkseInleg=1700; rendementTotaal=559000; groepen=13; kaarten=16',
      source: 'som current_value over PERSONAS.compleet.assets + PERSONAS.compleet.bank_accounts (spiegelt perspectiveAssetValue/totalValue in components/core/assets-client.tsx r140-146,389 — in het solo-perspectief van een persona zonder huishouden is ownership altijd "personal", dus perspectiveAssetValue(asset) reduceert triviaal tot current_value; geen aparte weeglogica te herimplementeren)',
    },
  },
  {
    workflow: 'WF-BEZIT-02',
    scenarioId: 'UAT-BEZIT-02',
    titel: 'Bezittingen filteren op categorie',
    kriticiteit: 'OVERIG',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen op /overzicht/bezittingen.',
    when: 'De gebruiker kiest "Beleggingen" in de filter-dropdown, daarna "Alle bezittingen".',
    then: 'Alleen de groep Beleggingen (1 kaart) blijft zichtbaar; de figures-strip blijft ongewijzigd (drempellogica is filter-onafhankelijk); "Alle bezittingen" herstelt alle 13 groepen; een categorie zonder items toont geen lege groepskop.',
    assertion: {
      kind: 'ui-only',
    },
  },
  {
    workflow: 'WF-BEZIT-03',
    scenarioId: 'UAT-BEZIT-03',
    titel: 'Verdeling & projectie raadplegen',
    kriticiteit: 'BELANGRIJK',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen; kaart "Verdeling & Projectie" opengeklapt.',
    when: 'De gebruiker bekijkt de allocatie-donut en wisselt de projectiehorizon (5j/10j/20j/30j).',
    then: 'Donut-percentages: Eigen huis 35,3% (560.000/1.585.000), Beleggingen 18,9% (300.000/1.585.000), Deelneming 11,4% (180.000/1.585.000); de eindwaarde stijgt monotoon per horizonstap. Steekproef: de Meesman-deelreeks (P=300.000, C=1.500/mnd, r=7%) na 5 jaar (60 maanden) = €532.676,93 — de motor compoundt MAANDELIJKS, niet jaarlijks. LET OP: dit wijkt af van de jaarlijks-samengestelde vingeroefening in Deel 2 (~€524.278); €532.676,93 is het correcte, motor-getrouwe cijfer.',
    assertion: {
      kind: 'exact',
      expected: 532676.93,
      source: 'lib/asset-data.ts#projectAsset(300000, 7, 1500, 60) — laatste maand (m=60); donut-percentages = categorie current_value / totale waarde (zelfde bron als WF-BEZIT-01)',
    },
  },
  {
    workflow: 'WF-BEZIT-04',
    scenarioId: 'UAT-BEZIT-04',
    titel: 'Inspiratie-inzichten gebruiken en minimaliseren',
    kriticiteit: 'OVERIG',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen (liquide cash €64.000 ≥ €10.000-drempel; belegd vermogen €300.000 ≥ €25.000-drempel — beide inzichtkaarten actief).',
    when: 'De compound-slider wordt op €500/mnd gezet (principal €0, 30 jaar); de fee-slider op 1% extra kosten (Meesman-positie €300.000/€1.500 mnd, 30 jaar, 7% vs 6%).',
    then: 'Compound-vergelijking: conservatief (0,5%) €193.680, ambitieus (7%) €566.765, verschil €373.085, multiplier ≈2,93 (≥1,05 dus zichtbaar). Fee-impact: eindwaarde@7% €3.983.971 vs eindwaarde@6% €3.146.095, kostenimpact €837.876.',
    assertion: {
      kind: 'exact',
      expected: 'conservatief=193680; ambitieus=566765; verschil=373085; fee7=3983971; fee6=3146095; feeImpact=837876',
      source: 'lib/compound-projection.ts#compareCompound({principal:0, monthlyContribution:500, years:30, conservativeRate:0.005, ambitiousRate:0.07}) en #projectCompound(300000,1500,30,0.07 / 0.06)',
    },
  },
  {
    workflow: 'WF-BEZIT-05',
    scenarioId: 'UAT-BEZIT-05',
    titel: 'Bezitting toevoegen (QuickAdd-wizard)',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen (Totale waarde €1.585.000).',
    when: 'De gebruiker voegt via QuickAdd een bezit "Spaarrekening extra" (type Spaargeld, waarde €5.000) toe.',
    then: 'Totale waarde stijgt naar €1.590.000 (directe optelling, geen weglogica voor een nieuwe persoonlijke bezitting).',
    assertion: {
      kind: 'exact',
      expected: 1590000,
      source: 'PERSONAS.compleet totale waarde (1.585.000) + nieuwe current_value (5.000) — components/core/assets-client.tsx totalValue-reduce',
    },
  },
  {
    workflow: 'WF-BEZIT-06',
    scenarioId: 'UAT-BEZIT-06',
    titel: 'Bezitting bekijken via kaart-klik (detail-pane)',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen.',
    when: 'De gebruiker klikt de kaarten "Belang Volkert Compleet Holding BV" (deelneming), "Eigen woning Amersfoort" (eigen_huis) en "Meesman Wereldwijd Totaal" (investment, holdings-tracking).',
    then: 'Deelneming: rendement 900,0% ((180.000−18.000)/18.000×100); gekoppelde DGA-schuld "Rekening-courant schuld BV" €9.000 ≪ €500.000-drempel ⇒ geen waarschuwing. Eigen woning: overwaarde €260.000 (560.000−300.000 hypotheeksaldo), rendement 36,6% ((560.000−410.000)/410.000×100). Meesman: banner "Portfolio tracker actief"; holdings-waarde (2.215×€135,48=€300.088,20) wijkt af van het vaste current_value-veld (€300.000) — bekende, gedocumenteerde discrepantie (zie testrapport), geen hard defect.',
    assertion: {
      kind: 'exact',
      expected: 'deelnemingRendement=900.0; woningOverwaarde=260000; woningRendement=36.585365853658536; meesmanHoldingsValue=300088.2',
      source: 'rendement% = (current_value−purchase_value)/purchase_value×100 op PERSONAS.compleet.assets; overwaarde = current_value(eigen_huis)−current_balance(gekoppelde hypotheek uit PERSONAS.compleet.debts); meesmanHoldingsValue = units×current_price op PERSONAS.compleet.holdings[0]',
    },
  },
  {
    workflow: 'WF-BEZIT-07',
    scenarioId: 'UAT-BEZIT-07',
    titel: 'Bezitting bewerken (incl. app-koppelingen en verkoopstrategie)',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen; asset "Auto (elektrisch)" wordt bewerkt.',
    when: 'De gebruiker stelt de verkoopstrategie in: "Vast moment" op leeftijd 45, verkoopkosten 2%, af te lossen schuld "Autolening (restant)".',
    then: 'De opgeslagen sale_config is {stand:"vast_moment", triggerAge:45, salesCostsPct:0.02, payoffDebtIds:["<autolening-id>"]} — de parser laat 0,02 ongewijzigd (binnen de geldige [0, 0,20]-range) en verzint geen velden bij.',
    assertion: {
      kind: 'exact',
      expected: '{stand:"vast_moment",triggerAge:45,salesCostsPct:0.02,payoffDebtIds:["debt-autolening"]}',
      source: 'lib/sale-config.ts#parseSaleConfig — parse-met-fallback, salesCostsPct alleen behouden binnen [0, 0.2]',
    },
  },
  {
    workflow: 'WF-BEZIT-08',
    scenarioId: 'UAT-BEZIT-08',
    titel: 'Eén bezitting herwaarderen',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen; "Kunst + sieraden" staat op €14.000.',
    when: 'De gebruiker herwaardeert "Kunst + sieraden" naar €15.000 (peildatum vandaag).',
    then: 'Totale waarde stijgt naar €1.586.000 (1.585.000 + 1.000 delta).',
    assertion: {
      kind: 'exact',
      expected: 1586000,
      source: 'PERSONAS.compleet totale waarde (1.585.000) + delta (15.000−14.000)',
    },
  },
  {
    workflow: 'WF-BEZIT-09',
    scenarioId: 'UAT-BEZIT-09',
    titel: 'Alles herwaarderen (bulk)',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen; huidig totaal €1.585.000.',
    when: 'De gebruiker wijzigt in de bulk-herwaardeerpagina "Kunst + sieraden" €14.000→€15.000 (+1.000) en "Auto (elektrisch)" €28.000→€25.000 (−3.000); "Meesman Wereldwijd Totaal" is vergrendeld (holdings-beheerd).',
    then: 'Netto delta = (+1.000)+(−3.000) = −€2.000; nieuw totaal €1.583.000.',
    assertion: {
      kind: 'exact',
      expected: 1583000,
      source: 'app/(app)/core/assets/revalue/page.tsx — som van per-rij delta’s toegepast op PERSONAS.compleet totale waarde',
    },
  },
  {
    workflow: 'WF-BEZIT-10',
    scenarioId: 'UAT-BEZIT-10',
    titel: 'Bezitting verwijderen',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen; huidig totaal €1.585.000.',
    when: 'De gebruiker verwijdert (a) "Aanhangwagen + gereedschap" (€6.000, enige in groep "Overig") of (b) "Eigen woning Amersfoort" (€560.000, randgeval grootste bezitting).',
    then: '(a) Totale waarde daalt naar €1.579.000, groep "Overig" verdwijnt volledig. (b) Totale waarde daalt naar €1.025.000.',
    assertion: {
      kind: 'exact',
      expected: 'happyPath=1579000; grootsteVerwijderd=1025000',
      source: 'PERSONAS.compleet totale waarde minus current_value van de verwijderde asset (soft delete — is_active=false, buiten de totalValue-reduce) via `DELETE /api/assets/[id]` (app/api/assets/[id]/route.ts) — sinds de omzetting naar een API-route géén client-directe update meer',
    },
  },
  {
    workflow: 'WF-BEZIT-11',
    scenarioId: 'UAT-BEZIT-11',
    titel: 'Categoriepagina per bezittype bekijken',
    kriticiteit: 'BELANGRIJK',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen.',
    when: 'De gebruiker opent de categoriepagina "Beleggingen" (/overzicht/bezittingen/investment of /core/assets/investment — identieke UI, pure re-export).',
    then: 'Mini-hero toont "1 positie", categorie-totaal €300.000 (het vaste current_value-veld van de Meesman-asset, niet de holdings-som).',
    assertion: {
      kind: 'exact',
      expected: 300000,
      source: 'som current_value van PERSONAS.compleet.assets gefilterd op asset_type==="investment" (asset-category-page.tsx hero-totaal, r414-417)',
    },
  },
  {
    workflow: 'WF-BEZIT-12',
    scenarioId: 'UAT-BEZIT-12',
    titel: 'Aandelen-holdings-app openen en portfolio analyseren',
    kriticiteit: 'KERN',
    persona: 'willem',
    given: 'Persona Willem Jansen geladen (DEGIRO-portefeuille, 4 posities: VWRL 3.800@€110,53, IEAG 800@€100,00, TDIV 180@€250,00, EMIM 900@€27,78).',
    when: 'De gebruiker opent de tab "Aandelen holdings", sorteert op gewicht en bekijkt de allocatie-donut (asset-class).',
    then: 'Totale waarde €570.016 (420.014+80.000+45.000+25.002); VWRL bovenaan met gewicht 73,68%; equity 85,97% (VWRL+TDIV+EMIM), bonds 14,03% (IEAG); concentratie top-3 (VWRL+IEAG+TDIV) 95,61%. Randgeval: bij persona compleet (1 holding) is concentratie triviaal 100% en is de benchmark niet beschikbaar (drempel ≥2 holdings).',
    assertion: {
      kind: 'exact',
      expected: 'totaal=570016; equityPct=85.97; bondsPct=14.03; concentratieTop3Pct=95.61; vwrlWeightPct=73.68',
      source: 'som units×current_price over PERSONAS.willem.holdings (holdings-client.tsx totale waarde/allocatie-donut/concentratie-berekening)',
    },
  },
  {
    workflow: 'WF-BEZIT-13',
    scenarioId: 'UAT-BEZIT-13',
    titel: 'Koersen verversen en handmatig bijwerken',
    kriticiteit: 'BELANGRIJK',
    persona: 'willem',
    given: 'Persona Willem Jansen geladen; live koersdata is niet-deterministisch.',
    when: 'De gebruiker klikt "Vernieuwen" (live feed) en stelt daarna handmatig de TDIV-koers in op €260,00.',
    then: 'Vernieuwen: voor élke holding moet gelden waarde = eenheden × getoonde koers (consistentie, geen vast cijfer door de live feed). Handmatige override (wél exact): TDIV-waarde wordt €46.800 (180×260,00, was €45.000), verschil +€1.800, nieuw portfoliototaal €571.816 (570.016+1.800).',
    assertion: {
      kind: 'consistency',
      expected: 'override: tdivNieuweWaarde=46800; delta=1800; nieuwPortfolioTotaal=571816',
      source: 'consistentie-eis: getoonde waarde = eenheden×getoonde koers (holdings-client.tsx); override-tak is wél exact narekenbaar op PERSONAS.willem.holdings',
    },
  },
  {
    workflow: 'WF-BEZIT-14',
    scenarioId: 'UAT-BEZIT-14',
    titel: 'Holding handmatig toevoegen',
    kriticiteit: 'KERN',
    persona: 'willem',
    given: 'Persona Willem Jansen geladen (portefeuille €570.016).',
    when: 'De gebruiker voegt "Vanguard S&P 500 UCITS" (VUSA) toe: 50 eenheden @ €95,00, TER 0,07%.',
    then: 'Nieuwe kaart-waarde €4.750 (50×95); jaarkosten-preview €3,33 (0,0007×4.750); nieuw portfoliototaal €574.766 (570.016+4.750). Regressie (POST /api/holdings, WF-BEZIT-14-bug2): het doel-asset wordt server-side gevalideerd — een meegestuurd `asset_id` moet van de gebruiker zelf en actief zijn (400 "Onbekend vermogensobject" resp. "gearchiveerd" anders), en een crypto-asset wordt geweigerd (400, crypto loopt via de exchange-sync naar `crypto_holdings`, nooit via dit endpoint naar `investment_holdings`); zonder `asset_id` valt de route terug op het eerste actieve, holdings-trackende asset van de gebruiker (nooit een soft-deleted asset).',
    assertion: {
      kind: 'exact',
      expected: 'waarde=4750; jaarkosten=3.33; nieuwTotaal=574766',
      source: 'units×prijs (HoldingForm-preview) + PERSONAS.willem-portefeuillewaarde uit WF-BEZIT-12; asset-routing/validatie in app/api/holdings/route.ts (POST)',
    },
  },
  {
    workflow: 'WF-BEZIT-15',
    scenarioId: 'UAT-BEZIT-15',
    titel: 'Holding-transactie registreren (koop/verkoop/dividend)',
    kriticiteit: 'KERN',
    persona: 'willem',
    given: 'Persona Willem Jansen geladen — VWRL: volledige transactiehistorie (buy 1.500@68 + 800@72,50 + 700@78 + 800@82 + 3 dividenden); EMIM: buy 500@25 + 400@27,50.',
    when: 'De gebruiker koopt 200 VWRL @ €112,00, en verkoopt 100 EMIM @ €28,00.',
    then: 'VWRL: de ÉCHTE weighted-average uit de volledige transactiehistorie is €73,7368 (niet het afgeronde seed-veld avg_purchase_price=€73,68) — na de koop van 200@112 wordt het nieuwe gemiddelde €75,65, nieuwe units 4.000. EMIM: de échte weighted-average is €26,1111 (seed-veld 26,11 is hier wél een correcte afronding) — gerealiseerde winst bij verkoop €188,89 (100×(28,00−26,1111)), resterend 800 eenheden. LET OP — Deel 2 claimt €75,60 resp. €189,00: deze zijn afgeleid van het afgeronde seed-veld avg_purchase_price in plaats van de daadwerkelijke transactiehistorie; `computePositionFromTransactions` op de échte transacties levert €75,65 resp. €188,89 op (VWRL-verschil ≈€0,05/eenheid ≈€200 op de positie, EMIM-verschil ≈€0,11 — beide reken-afrondingen in Deel 2, geen defect in de holdings-aggregatie).',
    assertion: {
      kind: 'exact',
      expected: 'vwrlAvgBeforeBuy=73.736842105263158; vwrlNieuwGemiddelde=75.65; vwrlNieuweUnits=4000; emimAvgBeforeSell=26.111111111111111; emimGerealiseerd=188.888888888889; emimResterend=800',
      source: 'lib/holdings-aggregation.ts#computePositionFromTransactions op de volledige PERSONAS.willem.holdings-transactiehistorie (VWRL/EMIM) + de nieuwe koop/verkoop-transactie',
    },
  },
  {
    workflow: 'WF-BEZIT-16',
    scenarioId: 'UAT-BEZIT-16',
    titel: 'Holding bekijken/bewerken/verwijderen via de detail-pane',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen — Meesman-holding met 5 buy-transacties (58.800+49.920+46.440+43.920+27.060) + 1 dividend (€1.850), current_price €135,48.',
    when: 'De gebruiker opent de holdings-detail-pane van Meesman.',
    then: 'Totaal geïnvesteerd €226.140; gem. aankoopprijs €102,0948 (≈€102,09); gerealiseerd (alleen dividend, geen sells) €1.850,00; ongerealiseerd €73.948,20 ((135,48−102,0948)×2.215); totaal €75.798,20; huidige waarde €300.088,20 (2.215×135,48).',
    assertion: {
      kind: 'exact',
      expected: 'totalInvested=226140; avgCost=102.0948; realized=1850; unrealized=73948.2; totalPnL=75798.2; currentValue=300088.2',
      source: 'lib/holdings-aggregation.ts#computePositionFromTransactions + #valuePosition op PERSONAS.compleet.holdings[0].transactions',
    },
  },
  {
    workflow: 'WF-BEZIT-17',
    scenarioId: 'UAT-BEZIT-17',
    titel: 'Holding-detailpagina: alerts, Box 3, TER en favoriet',
    kriticiteit: 'KERN',
    persona: 'willem',
    given: 'Persona Willem Jansen geladen (DEGIRO-portefeuille €570.016, single, geen fiscaal partner). TDIV: 180 eenheden, gem. €228,47, huidig €250,00, TER 1,20%.',
    when: 'De gebruiker opent de TDIV-detailpagina.',
    then: 'Rendement 9,45% ((250,00−228,47)/228,47×100). Box 3 (2026, single): portfolioaandeel 7,8945%, toegerekend heffingsvrij vermogen €4.685,95, belastbaar €40.314,05, forfaitrendement (6,00%) €2.418,84, heffing (36%) €870,78, effectief tarief 1,94%. Dit effectieve tarief geldt identiek voor VWRL/IEAG/EMIM (evenredige toerekening over de hele portefeuille). TER-jaarkosten €540,00 (1,20%×45.000). LET OP — Deel 2 claimt €4.685,60 voor de toegerekende vrijstelling; het onafhankelijk narekende cijfer is €4.685,95 (verschil ≈€0,35, een kleine reken-slip in Deel 2 die de headline 1,94% niet raakt).',
    assertion: {
      kind: 'exact',
      expected: 'rendementPct=9.45; portfolioShare=0.0789451524; allocatedExemption=4685.95; taxableValue=40314.05; forfaitRendement=2418.84; annualTax=870.78; effectiveRatePct=1.94; terJaarkosten=540',
      source: 'lib/box3-holdings.ts#calculateHoldingBox3(45000, 570016, false, 2026) — BOX3_PARAMS[2026] uit lib/box3-data.ts (heffingsvrijSingle=59.357, forfaitBeleggingen=0.06, tarief=0.36)',
    },
  },
  {
    workflow: 'WF-BEZIT-18',
    scenarioId: 'UAT-BEZIT-18',
    titel: 'Holdings importeren via CSV (broker-export)',
    kriticiteit: 'KERN',
    persona: 'daan',
    given: 'Persona Daan Bakker geladen. Trading212-CSV met IWDA (buy 10@75, buy 10@80, sell 5@90, dividend 15@0,20) en EUNL (buy 5@85). LET OP — Deel 2 claimt "geen bestaande holdings"; PERSONAS.daan.holdings bevat in werkelijkheid al 2 posities (Meesman Wereldwijd Totaal + Brand New Day Pensioen), dus dit scenario draait in de praktijk in append/merge-modus bovenop een niet-lege lijst, niet op een lege lijst zoals Deel 2 veronderstelt. De wizard eist sindsdien een expliciete doel-bezitting: de merge blijft binnen die ene bezitting in plaats van over de hele portefeuille.',
    when: 'De gebruiker kiest een doel-bezitting (of laat er een aanmaken), importeert het bestand en bevestigt alle 5 rijen. Een Trading 212-export is een transactiehistorie, dus de wizard kiest de aanvul-modus — er wordt niets als verkocht gemarkeerd.',
    then: 'IWDA: na 2 koop-transacties gem. €77,50 (750+800=1.550/20 eenheden); na verkoop van 5 @ €90: gerealiseerd €62,50 (5×(90−77,50)), 15 eenheden over; + dividend €3,00 ⇒ totaal gerealiseerd €65,50. EUNL: 5 eenheden, gem. €85,00. Totale import-waarde in de samenvattingsbalk €2.428,00 (750+800+450+3+425).',
    assertion: {
      kind: 'exact',
      expected: 'iwdaAvgAfter2Buys=77.5; iwdaRealizedOnSell=62.5; iwdaUnitsAfterSell=15; iwdaTotalRealizedInclDiv=65.5; eunlUnits=5; eunlAvg=85; importTotal=2428',
      source: 'lib/holdings-aggregation.ts#computePositionFromTransactions op de CSV-transactierijen uit UAT-BEZIT-18',
    },
  },
  {
    workflow: 'WF-BEZIT-19',
    scenarioId: 'UAT-MIJN-18',
    titel: 'Trading 212-broker-koppeling beheren (koppelen, synchroniseren, loskoppelen)',
    kriticiteit: 'KERN',
    given: 'Een investment-asset met een actieve Trading 212-koppeling.',
    when: 'De gebruiker synchroniseert de koppeling.',
    then: 'De gesynchroniseerde positie telt identiek mee als een handmatige holding: waarde/eenheden op de koppelingskaart en op de holdings-rij zijn gelijk. Geen vast cijfer uit persona-seeds herleidbaar (geen enkele persona-seed bevat een broker_connections-rij) — getoetst als doorwerking in UAT-MIJN-18/UAT-BEZIT-12d, niet als los BEZIT-scenario.',
    assertion: {
      kind: 'consistency',
      source: 'consistentie-eis: koppelingskaart-waarde === holdings-rij-waarde na sync; server-gedrag van de sync (lib/integrations/trigger-sync.ts) is in Deel 1 gemarkeerd als "Onbevestigd"',
    },
  },
  {
    workflow: 'WF-BEZIT-20',
    scenarioId: 'UAT-MIJN-18',
    titel: 'Crypto exchange-/wallet-koppeling beheren',
    kriticiteit: 'KERN',
    given: 'Een crypto-asset met een actieve exchange- of wallet-koppeling.',
    when: 'De gebruiker synchroniseert de koppeling.',
    then: 'Gesynchroniseerde coin-saldi tellen identiek mee als handmatige holdings (zelfde consistentie-eis als WF-BEZIT-19, hier voor crypto). Geen vast cijfer uit persona-seeds herleidbaar.',
    assertion: {
      kind: 'consistency',
      source: 'consistentie-eis: koppelingskaart-waarde === crypto-holdings-grid-waarde na sync; getoetst als doorwerking in UAT-BEZIT-21d',
    },
  },
  {
    workflow: 'WF-BEZIT-21',
    scenarioId: 'UAT-BEZIT-21',
    titel: 'Crypto-holdings-app gebruiken (analyse per coin)',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen; "Holdings bijhouden" gezet op de crypto-asset; 2 coins handmatig toegevoegd: BTC 0,5@ gem. €25.000/huidig €58.000; ETH 3@ gem. €2.000/huidig €3.200.',
    when: 'De gebruiker bekijkt de KPI-strip en het verdelings-paneel "Per coin".',
    then: 'Totale waarde €38.600 (BTC €29.000 + ETH €9.600); indicatieve Box 3-heffing €833,76 (38.600×6%×36%); ongerealiseerd P&L totaal €20.100 (BTC €16.500 + ETH €3.600); verdeling BTC 75,13% / ETH 24,87%. Regressie: deze tab crashte eerder in productie met React #300 (error-boundary "Je gegevens zijn veilig") zodra de setup-gate een sectie-interne state-update kreeg; secties in AppSetupGate worden nu als echte componenten gemount, geen crash meer.',
    assertion: {
      kind: 'exact',
      expected: 'totaal=38600; box3Indicatief=833.76; unrealizedTotal=20100; btcPct=75.13; ethPct=24.87',
      source: 'som units×current_price + (current_price−avg_purchase_price)×units op de 2 handmatig toegevoegde BTC/ETH-posities; Box3-indicatie = totaal×0,06×0,36 (2026-forfait, geen vrijstelling verrekend — crypto-kpi-strip.tsx)',
    },
  },
  {
    workflow: 'WF-BEZIT-22',
    scenarioId: 'UAT-BEZIT-22',
    titel: "Typed holding-detailpagina's (crypto-coin / investment-positie)",
    kriticiteit: 'BELANGRIJK',
    persona: 'compleet',
    given: 'Vervolg op UAT-BEZIT-21: BTC-coin aanwezig (0,5 eenheden @ gem. €25.000, huidig €58.000).',
    when: 'De gebruiker opent de BTC-detailpagina.',
    then: 'Waarde €29.000 (0,5×58.000); kostenbasis €12.500 (0,5×25.000); rendement 132,0% ((29.000−12.500)/12.500×100). Regressie: beide typed detailpagina\'s (crypto en investment) delen sinds deze release dezelfde `HoldingFavoriteButton` (components/holdings/holding-favorite-button.tsx, ook gebruikt op de generieke holdings/[id]-pagina); favoriet aan/uit zet `is_favorite` op de holding en werkt door in de dashboard-favorieten-widget (reverse-sync bij verwijderen, zie WF-OVZ-08) — geen eigen berekening.',
    assertion: {
      kind: 'exact',
      expected: 'waarde=29000; kostenbasis=12500; rendementPct=132.0',
      source: 'units×current_price en (waarde−kostenbasis)/kostenbasis×100 op dezelfde BTC-positie als WF-BEZIT-21',
    },
  },
  {
    workflow: 'WF-BEZIT-23',
    scenarioId: 'UAT-BEZIT-23',
    titel: 'Verhuurrendement-tool gebruiken (vastgoed)',
    kriticiteit: 'KERN',
    persona: 'compleet',
    given: 'Persona Tessa Compleet geladen — "Verhuurd appartement Utrecht" (€185.000, huur €950/mnd, geen onderhoud-override) + gekoppelde "Beleggingshypotheek appartement" (€110.000 @ 3,6%, aflossingsvrij).',
    when: 'De gebruiker bekijkt de KPI-hero, de Box 3-vergelijking en schuift de waardestijging-slider (default 2,5%); als randgeval wordt de hypotheekrente tijdelijk op 8% gezet.',
    then: 'Eigen geld €75.000 (185.000−110.000); maandelijkse netto cashflow €465,83 (950−330,00 rente−154,17 onderhoud[1%-schatting]); jaarcashflow €5.590; forfaitrendement €11.100 (185.000×6%), forfaitbelasting €3.996 (×36%), netto na forfait €1.594, forfait-ROI ≈2,13% (1.594/75.000); waardestijging/jr €4.625 (185.000×2,5%). Randgeval rente 8%: maandrente €733,33 (110.000×8%/12) — LET OP: Deel 2 claimt dat de netto cashflow dan NEGATIEF wordt (−€937,50≈, "950−733,33−154,17"), maar diezelfde som (950−733,33−154,17) is onafhankelijk narekenbaar op **+€62,50** (nog altijd positief; €733,33 < €950 huur, dus de eigen aanname "> huur" in Deel 2 is zelf al onjuist) — een reken-fout in Deel 2, geen defect in `calculateRental`.',
    assertion: {
      kind: 'exact',
      expected: 'eigenGeld=75000; maandCashflow=465.83; forfaitRendement=11100; forfaitBelasting=3996; nettoNaForfait=1594; forfaitROIPct=2.13; waardestijgingPerJaar=4625; randgevalMaandRente8pct=733.33; randgevalCashflow=62.5',
      source: 'components/core/deepenings/verhuurrendement/calc.ts#calculateRental — NL_FICTIEF_BELEGGINGEN=0.06 en BOX3_TARIEF=0.36 (2026, lib/constants.ts)',
    },
  },
  {
    workflow: 'WF-BEZIT-24',
    scenarioId: 'UAT-BEZIT-24',
    titel: 'Eigendom van een bezitting, rekening of transactie instellen (persoonlijk/gedeeld)',
    kriticiteit: 'KERN',
    given: 'Twee testaccounts (ronald@test.trifinity.nl als eigenaar, bas@test.trifinity.nl als partner) in een huishouden met split_mode "equal" — geen persona-seed bevat een geaccepteerd huishoudlid.',
    when: 'Account A voegt een gedeelde bezitting "Gedeelde camper" (€20.000, ownership=shared) toe en wisselt tussen de perspectieven "Eigen" en "Huishouden".',
    then: 'Bij split_mode "equal" is het aandeel altijd 50/50: eigen-perspectief toont €10.000 (20.000×50%); huishoud-perspectief toont de volle €20.000 (gedeeld telt altijd 100% mee in het huishoud-perspectief).',
    assertion: {
      kind: 'exact',
      expected: 'sharePct=50; eigenAandeel=10000; huishoudPerspectief=20000',
      source: 'lib/household-data.ts#computeSharePct({splitMode:"equal", customSplitPct:null, primaryPayerId:null}, userId) → 50, toegepast op een gedeeld bezit van €20.000',
    },
  },
  {
    workflow: 'WF-BEZIT-25',
    scenarioId: 'UAT-BEZIT-25',
    titel: 'Koppelscherm bij nul gekoppelde bezittingen (crypto-/aandelen-holdings-app)',
    kriticiteit: 'BELANGRIJK',
    given: 'De eenmalige app-setup van de Crypto-holdings-app resp. Aandelen-holdings-app is voltooid, maar geen enkele bezitting van het juiste type heeft `has_holdings_tracking` aan (alle crypto- resp. investment-bezittingen ontkoppeld of nog geen enkele toegevoegd).',
    when: 'De gebruiker opent de tab "Crypto holdings" (/overzicht/bezittingen/crypto?tab=crypto-holdings, canoniek /core/assets/crypto) resp. "Aandelen holdings" (/overzicht/bezittingen/investment?tab=aandelen-holdings).',
    then: '`AppLinkGate` toont een hero-band "Bezittingen koppelen" + checkbox-lijst met kandidaten (naam + bedrag) i.p.v. een doodlopende empty-state; de knop "Koppelen" blijft disabled zonder selectie. Opslaan POST\'t per geselecteerd item `{id, enabled:true}` naar `/api/assets/toggle-holdings` (dezelfde vlag als de instelling op de bezitting zelf) en ververst de tab, waarna de normale holdings-app rendert. Zijn er geen kandidaten van het juiste type (nul crypto- resp. investment-bezittingen), dan toont het scherm i.p.v. de checkbox-lijst een voeg-eerst-toe-tekst met CTA naar de items-tab. Zijdelings: de losstaande "Geen crypto-posities"-empty-state (wél gekoppeld, nul holdings-rijen) linkt sinds deze release naar `/mijn/koppelingen` i.p.v. het verwijderde `/identity/koppelingen`.',
    assertion: {
      kind: 'ui-only',
      source: 'components/app/app-setup/app-link-gate.tsx (generiek koppelscherm) + components/core/deepenings/crypto-holdings-tab.tsx / investment-holdings-tab.tsx (filter has_holdings_tracking===false op alle assets van het type → candidates; endpoint /api/assets/toggle-holdings)',
    },
  },
  {
    workflow: 'WF-BEZIT-26',
    scenarioId: 'UAT-BEZIT-26',
    titel: 'Portfoliorendement vergelijken met AEX/MSCI World/S&P 500 (tijdgewogen, periode-gebonden)',
    kriticiteit: 'BELANGRIJK',
    persona: 'willem',
    given: 'Persona Willem Jansen met minstens twee aandelen-holdings (drempel voor een zinvolle vergelijking). `GET /api/benchmark-comparison?period=<id>` levert `compareToBenchmarks` op basis van de portefeuillehistorie (`buildPortfolioHistory`) en live Yahoo Finance-koersreeksen per index (`^AEX`, `IWDA.AS`, `^GSPC`), met een synthetische fallback per benchmark wanneer die koersreeks ontbreekt.',
    when: 'De gebruiker opent de Aandelen-holdings-app (`components/core/holdings-client.tsx` / `portfolio-summary.tsx`) en bekijkt de benchmark-grafiek (`BenchmarkComparisonChart`), wisselt van periode (1m/3m/6m/1j/all — `TIME_PERIODS`).',
    then: 'Het benchmarkvenster volgt de gekozen periode (`resolveComparisonWindow`) — dezelfde functie bepaalt zowel de Yahoo-fetch als de knip in de vergelijking, INCLUSIEF de terugval op de volledige historie bij te weinig snapshots, dus venster en cijfers kunnen niet uiteenlopen. Begint de koershistorie later dan de gekozen periode, dan schuift het venster mee voor portfolio én indices (`windowClipped`) en benoemt het label die kortere periode. Het portfoliorendement is tijdgewogen (TWR: r_t = O_t/(O_{t-1}+G_t)-1, samengesteld over de periode) en meet het WAARNEEMBARE deel van de portefeuille: posities zonder koersbron (turbo\'s, sprinters, delistings) blijven buiten teller én noemer in plaats van het hele venster te blokkeren, en een positie die dat mandje in- of uitstapt telt als kasstroom — nooit inleg-vervuild doordat stortingen of aangroeiende koersdekking als koerswinst meetellen. De hardheid van het getal reist mee als `portfolio.observedShare` (de zwakste gemeten maand) en de UI benoemt dat aandeel zodra het onder 100% ligt. Is er in het venster geen twee maanden koershistorie (`gap: \'no_price_history\'`) of overtrof een opname de startwaarde (`gap: \'unmeasurable_window\'`), dan toont de UI GEEN percentage en GEEN alpha — met de bijbehorende reden, nooit een misleidend cijfer of stille 0%. Bij minder dan twee holdings is de vergelijking niet beschikbaar (zie de drempel-randgeval in UAT-BEZIT-12). Elke `GET`-respons draagt `code: \'GEEN_HOLDINGS\'` bij lege portefeuille en gebruikt de gedeelde error-envelope (`unauthorized()`/`serverError()`) i.p.v. een losse foutvorm — een echte DB-/RLS-fout op de holdings-query wordt niet meer stil als "geen holdings" gepresenteerd.',
    assertion: {
      kind: 'consistency',
      source: 'app/api/benchmark-comparison/route.ts + lib/benchmark-comparison.ts#resolveComparisonWindow/compareToBenchmarks/buildPortfolioHistory/computeTwrOutcome/fetchAllRealBenchmarkData + components/app/benchmark-comparison-chart.tsx + components/core/holdings/portfolio-summary.tsx — live Yahoo Finance-afhankelijk, geen hand-narekenbaar exact-cijfer; consistentie-eis is venster-identiek tussen fetch en vergelijking, zie lib/architecture/calculations.ts#portfolio-benchmarkvergelijking',
    },
  },
]

export const BEZIT_ACCEPTANCE: AcceptanceSet = {
  zone: 'BEZIT',
  criteria,
}
