'use client'

import { useEffect, useState } from 'react'

interface Test {
  name: string
  pass: boolean
  detail: string
}

interface ApiResponse {
  status: string
  feature: number
  featureName: string
  year: number
  passing: number
  total: number
  allPassing: boolean
  tests: Test[]
  summary: {
    dbAssetCount: number
    dbDebtCount: number
    dailyExpenses: string
    belasting: string
    vrijheidsdagen: number
    optimizationCount: number
  }
  error?: string
}

export default function TestBox3Optimization() {
  const [result, setResult] = useState<ApiResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch('/api/verify-box3-optimization')
      .then(r => r.json())
      .then(data => {
        setResult(data)
        setLoading(false)
      })
      .catch(err => {
        setError(String(err))
        setLoading(false)
      })
  }, [])

  if (loading) {
    return (
      <div className="mx-auto max-w-3xl p-8">
        <h1 className="text-2xl font-bold mb-4">Loading Box 3 Optimization Tests...</h1>
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-amber-500 border-t-transparent" />
      </div>
    )
  }

  if (error || !result) {
    return (
      <div className="mx-auto max-w-3xl p-8">
        <h1 className="text-2xl font-bold mb-4 text-red-700">Error</h1>
        <p className="text-red-600">{error || 'Unknown error'}</p>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-3xl p-8 space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Feature #129: Box 3 Tax Optimization Verification</h1>
        <p className="text-zinc-500 mt-1">{result.featureName}</p>
      </div>

      {/* Summary Banner */}
      <div className={`rounded-xl p-6 ${
        result.allPassing
          ? 'border-2 border-emerald-300 bg-emerald-50'
          : 'border-2 border-red-300 bg-red-50'
      }`}>
        <div className="flex items-center justify-between">
          <div>
            <p className={`text-lg font-bold ${result.allPassing ? 'text-emerald-700' : 'text-red-700'}`}>
              {result.allPassing ? '✅ ALL TESTS PASSING' : `❌ ${result.total - result.passing} TEST(S) FAILING`}
            </p>
            <p className="text-sm text-zinc-600 mt-1">
              {result.passing}/{result.total} tests passing for year {result.year}
            </p>
          </div>
          <div className="text-right text-sm text-zinc-600">
            <p>DB Assets: {result.summary.dbAssetCount}</p>
            <p>DB Debts: {result.summary.dbDebtCount}</p>
            <p>User Tax: €{result.summary.belasting}</p>
            <p>Freedom days: {result.summary.vrijheidsdagen}</p>
            <p>Optimizations: {result.summary.optimizationCount}</p>
          </div>
        </div>
      </div>

      {/* Individual Tests */}
      <div className="space-y-3">
        {result.tests.map((test, i) => (
          <div
            key={i}
            className={`rounded-xl border p-4 ${
              test.pass
                ? 'border-emerald-200 bg-emerald-50/50'
                : 'border-red-200 bg-red-50/50'
            }`}
          >
            <div className="flex items-start gap-3">
              <span className="text-lg mt-0.5" data-testid={`test-${i}-status`}>
                {test.pass ? '✅' : '❌'}
              </span>
              <div className="flex-1">
                <p className={`font-medium text-sm ${test.pass ? 'text-emerald-800' : 'text-red-800'}`}>
                  {test.name}
                </p>
                <p className="text-xs text-zinc-500 mt-1 break-all">{test.detail}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Data Source Confirmation */}
      <div className="rounded-xl border border-zinc-200 bg-zinc-50 p-4">
        <h3 className="font-semibold text-sm text-zinc-700 mb-2">Data Source Confirmation</h3>
        <p className="text-xs text-zinc-500">
          All data is queried from Supabase tables: <code className="bg-white px-1 rounded">assets</code>,{' '}
          <code className="bg-white px-1 rounded">debts</code>, and{' '}
          <code className="bg-white px-1 rounded">transactions</code>.
          The Box 3 calculation engine (<code className="bg-white px-1 rounded">calculateBox3()</code>) is a pure function
          that takes real asset/debt data as input and returns tax calculations using official Dutch tax parameters.
          Optimizations are generated by <code className="bg-white px-1 rounded">generateBox3Optimizations()</code>
          which uses the same real data to calculate concrete savings amounts and freedom days.
        </p>
      </div>
    </div>
  )
}
