import { BUDGET_SLUGS } from '../budget-data'
import type { SeedBudget } from './index'

export function getStarterBudgets(): SeedBudget[] {
  const S = BUDGET_SLUGS
  return [
    {
      name: 'Inkomen',
      slug: S.INKOMEN,
      icon: 'Wallet',
      description: 'Alle inkomstenbronnen',
      default_limit: 2000,
      budget_type: 'income',
      is_essential: true,
      priority_score: 5,
      sort_order: 0,
      children: [
        { name: 'Salaris & uitkering', slug: S.SALARIS_UITKERING, icon: 'Banknote', description: 'Netto salaris of uitkering', default_limit: 1800 },
        { name: 'Toeslagen & kinderbijslag', slug: S.TOESLAGEN_KINDERBIJSLAG, icon: 'Baby', description: 'Overheidstoeslagen en kinderbijslag', default_limit: 0 },
        { name: 'Teruggave belasting', slug: S.TERUGGAVE_BELASTING, icon: 'Receipt', description: 'Belastingteruggave', default_limit: 0 },
        { name: 'Overige inkomsten', slug: S.OVERIGE_INKOMSTEN, icon: 'HandCoins', description: 'Bijverdiensten en overig', default_limit: 200 },
      ],
    },
    {
      name: 'Vaste lasten wonen & energie',
      slug: S.VASTE_LASTEN_WONEN,
      icon: 'Home',
      description: 'Alle vaste woonlasten',
      default_limit: 960,
      budget_type: 'expense',
      is_essential: true,
      priority_score: 5,
      sort_order: 1,
      children: [
        { name: 'Huur / hypotheek', slug: S.HUUR_HYPOTHEEK, icon: 'Building2', description: 'Maandelijkse woonkosten', default_limit: 700 },
        { name: 'Gas, water, licht', slug: S.GAS_WATER_LICHT, icon: 'Zap', description: 'Energie en waterrekening', default_limit: 130 },
        { name: 'Verzekeringen wonen & gezondheid', slug: S.VERZEKERINGEN_WONEN, icon: 'ShieldCheck', description: 'Zorg-, woon- en inboedelverzekering', default_limit: 100 },
        { name: 'Gemeentelijke & overige vaste lasten', slug: S.GEMEENTELIJKE_LASTEN, icon: 'Landmark', description: 'OZB, afvalstoffenheffing, rioolheffing', default_limit: 30 },
      ],
    },
    {
      name: 'Dagelijkse uitgaven',
      slug: S.DAGELIJKSE_UITGAVEN,
      icon: 'ShoppingCart',
      description: 'Dagelijkse boodschappen en huishouden',
      default_limit: 310,
      budget_type: 'expense',
      is_essential: true,
      priority_score: 5,
      sort_order: 2,
      children: [
        { name: 'Boodschappen', slug: S.BOODSCHAPPEN, icon: 'Store', description: 'Supermarkt en voeding', default_limit: 250 },
        { name: 'Huishouden & verzorging', slug: S.HUISHOUDEN_VERZORGING, icon: 'SprayCan', description: 'Schoonmaak en persoonlijke verzorging', default_limit: 40 },
        { name: 'Kinderen & school/opvang', slug: S.KINDEREN_SCHOOL, icon: 'Baby', description: 'Schoolgeld, opvang, kinderkosten', default_limit: 0 },
        { name: 'Medische kosten', slug: S.MEDISCHE_KOSTEN, icon: 'HeartPulse', description: 'Eigen risico, medicijnen, tandarts', default_limit: 20 },
      ],
    },
    {
      name: 'Vervoer',
      slug: S.VERVOER,
      icon: 'Car',
      description: 'Alle vervoerskosten',
      default_limit: 75,
      budget_type: 'expense',
      is_essential: true,
      priority_score: 4,
      sort_order: 3,
      children: [
        { name: 'Brandstof / laden & OV', slug: S.BRANDSTOF_OV, icon: 'Fuel', description: 'Benzine, elektrisch laden, OV', default_limit: 60 },
        { name: 'Auto vaste lasten', slug: S.AUTO_VASTE_LASTEN, icon: 'CarFront', description: 'Wegenbelasting, verzekering, leasekosten', default_limit: 0 },
        { name: 'Auto onderhoud & parkeren', slug: S.AUTO_ONDERHOUD, icon: 'Wrench', description: 'APK, reparaties, parkeren', default_limit: 0 },
        { name: 'Fiets / deelvervoer', slug: S.FIETS_DEELVERVOER, icon: 'Bike', description: 'Fietsonderhoud, deelscooter', default_limit: 15 },
      ],
    },
    {
      name: 'Leuke dingen & lifestyle',
      slug: S.LEUKE_DINGEN,
      icon: 'PartyPopper',
      description: "Ontspanning, hobby's en plezier",
      default_limit: 210,
      budget_type: 'expense',
      is_essential: false,
      priority_score: 2,
      sort_order: 4,
      children: [
        { name: 'Uit eten, horeca & afhalen', slug: S.UIT_ETEN_HORECA, icon: 'UtensilsCrossed', description: 'Restaurants, cafés, bezorging', default_limit: 60 },
        { name: "Vrije tijd, hobby's & sport", slug: S.VRIJE_TIJD_SPORT, icon: 'Dumbbell', description: "Sport, streaming, hobby's", default_limit: 50 },
        { name: 'Vakantie & weekendjes weg', slug: S.VAKANTIE, icon: 'Palmtree', description: 'Vakanties en uitstapjes', default_limit: 60 },
        { name: 'Kleding & overige', slug: S.KLEDING_OVERIGE, icon: 'Shirt', description: 'Kleding, schoenen, accessoires', default_limit: 40 },
      ],
    },
    {
      name: 'Sparen & investeren',
      slug: S.SPAREN_SCHULDEN,
      icon: 'PiggyBank',
      description: 'Vermogensopbouw en buffer',
      default_limit: 120,
      budget_type: 'savings',
      is_essential: true,
      priority_score: 4,
      sort_order: 5,
      children: [
        { name: 'Sparen & noodbuffer', slug: S.SPAREN_NOODBUFFER, icon: 'Vault', description: 'Noodfonds en spaargeld', default_limit: 80 },
        { name: 'Investeren / FIRE / pensioen', slug: S.INVESTEREN_FIRE, icon: 'TrendingUp', description: 'Beleggingen en pensioenopbouw', default_limit: 40 },
      ],
    },
    {
      name: 'Schulden & aflossingen',
      slug: S.SCHULDEN_AFLOSSINGEN_PARENT,
      icon: 'CreditCard',
      description: 'Schulden aflossen en hypotheek',
      default_limit: 40,
      budget_type: 'debt',
      is_essential: true,
      priority_score: 4,
      sort_order: 6,
      children: [
        { name: 'Schulden & aflossingen', slug: S.SCHULDEN_AFLOSSINGEN, icon: 'CreditCard', description: 'Leningen en schulden aflossen', default_limit: 40 },
        { name: 'Extra aflossing hypotheek', slug: S.EXTRA_AFLOSSING_HYPOTHEEK, icon: 'HomeIcon', description: 'Vrijwillige extra hypotheekaflossing', default_limit: 0 },
      ],
    },
    {
      name: 'Eigen rekening',
      slug: S.EIGEN_REKENING,
      icon: 'ArrowLeftRight',
      description: 'Overboekingen tussen eigen rekeningen — geen invloed op resultaten',
      default_limit: 0,
      budget_type: 'archive',
      is_essential: false,
      priority_score: 1,
      sort_order: 99,
      children: [
        {
          name: 'Eigen rekening',
          slug: S.EIGEN_REKENING_SUB,
          icon: 'ArrowLeftRight',
          description: 'Overboekingen tussen eigen rekeningen',
          default_limit: 0,
        },
      ],
    },
  ]
}
